### ISSUE TITLE
No Value?

### ISSUE THREAD

**Issue by flipp3003** [MarcusCalidus/marcuscalidus-svg-panel#49]
I am currently using the plugin very intensively and I have the following problem: I get my check result cleanly "onHandleMetric (ctrl)" via the query. But if the host is down, then no check goes and the DB has no values. The select then gives no values. Is "onHandleMetric (ctrl)" called anyway? That would be important, because otherwise I cannot react to it in the presentation.
Best regards Thomas

**Comment by MarcusCalidus** [comment]
As far as I understand the Grafana technology onHandleMetric is called every time the metrics are refreshed (e.g. 15s) This has nothing to do with the fact if there are values available at all. 
You can call `console.log(ctrl.data)` in order to see in the browser's console how these "non existent" values manifest themselves there.

**Comment by flipp3003** [comment]
Sorry was my problem:

if (typeof ctrl.series [0] === 'undefined')
   return;

embarrassing...

Everything works fine now and I'm happy.
Your plugin is really a great idea. Much more flexible than that from Grafana. I have also tried to write a plugin and have made good progress, but your idea and implementation cannot be improved. So why reinvent the bike ???

Would like to show you my realization, but I don't know how to insert a picture here ...

I have a few more questions:
- You can remove all the samples. I already know her.
- Can I access the standard Grafana colors in the script (Ok, Warning, Critical)?
- I would like to use % values for representation, but there is one more error:
<rect x = "0%" y = "0%" width = "100%" height = "80" fill = "#ff0000"/>
If the panel is very small, the rectangle is drawn far beyond the edge of the panel.
I use Grafana 7.0.3

Best regards Thomas.

**Comment by MarcusCalidus** [comment]
Great you found the solution.

As regards your commendation, well, thank you. I guess there is an awful lot to improve. Especially the graphical layout is quite frustrating with the new Grafana version. But since this is only a side project I don't have much time at my hand. 

I really would love to see your implementation.

As for your ideas, it would be great if you could make an github issue out of each of them. So I can call for help in the open source community ;)

Have a great day, Marco

**Comment by flipp3003** [comment]
> I really would love to see your implementation.

Ok, gladly, but how can I send you the BMP PNG. I haven't found a way to integrate them into the community area here in Githab - email?
